### ISSUE TITLE
Mobile menu colors aren't readable

### ISSUE THREAD

**Issue by televators** [psychonautwiki/bifrost#6]
Wonderful and fantastic work, folks. I notcoed on the mobile menu that the background color is a dark grey and the text is black. It's barely readable. I'd recommend light text or a light background. You can run the color combination through a compliance checker for appropriate contrast.
Sincerely,
Random information architect and web designer/developer.

**Comment by televators** [comment]
Noticed* - second sentence.

**Comment by KenanSulayman** [comment]
Are you referring to the GraphiQL menu?

I assume you’re not actually talking about Bifrost and instead are referring to our mobile website.

It’s a known issue, albeit not the most critical one. I guess I’ll take care of the styling when I reintroduce our comprehensive mobile menu (https://github.com/psychonautwiki/4-aco-dmenut). JFYI / fun fact: I made the menu as dark as it is right now, because we previously applied a ‘filter: invert(100%);’

**Comment by KenanSulayman** [comment]
I went ahead and retrofitted 4-aco-dmenut, replacing the default menu (again).

![xxxxxx](https://user-images.githubusercontent.com/280212/35540889-619219d8-0558-11e8-8d17-d0a7ad7a7b6e.gif)

If you have further questions or input, drop by at https://github.com/psychonautwiki/4-aco-dmenut.
